### ISSUE TITLE
Bug: input with arity > 1

### ISSUE THREAD

**Issue by Fabiceju** [hbeck/ticker#5]
I have problems when I enter input with arity> 1. For example, given the following Lars program:
```
% verify that 2 different vehicles are going in the same direction
sameDirection: - possibleheading (D1), possiblecar (C1), heading (C1, D1), possibleheading (D2), possiblecar (C2), heading (C2, D2), C1! = C2, D1 = D2.
possibleheading (2) .possibleheading (3).
possiblecar (2) .possiblecar (3).
```

And giving as input the following predicate:

> Heading (2.3)

The input is seen as:

> Heading, 3)

And the model is still empty.
![direction_execution](https://user-images.githubusercontent.com/5691261/37781345-cf447014-2df0-11e8-85db-41035cd5e4e1.png)

**Comment by Nagelfar** [comment]
There was a clash in parsing multiple arguments. I fixed it & pushed already to master

But there is another issue with your program:

Because you are not using any window in the program the input signals are expired at the next timepoint after they are entered.
This is currently by design (as facts are only defined in the moment they when they were entered). 

Switching into another mode (when no windows are defined in a program) would be possible, but that would make ticker a plain ASP-Reasoner. You would need to discuss this with @hbeck  :-)

To solve this, you would need to:
- add either a window over the input signals
- provide them at the same timepoint as in the following screenshot

![inputs](https://user-images.githubusercontent.com/616204/37866167-1c01afba-2f87-11e8-9f49-97d9a359fa63.jpeg)
